name: smol-dria-terminal

ethereum:
  default_network: mainnet
  mainnet:
    default_provider: node

arbitrum:
  default_network: mainnet
  mainnet:
    default_provider: node

node:
  arbitrum:
    mainnet:
      uri: https://arbitrum.llamarpc.com
  ethereum:
    mainnet:
      uri: https://eth.llamarpc.com
  optimism:
    mainnet:
      uri: https://optimism.llamarpc.com

plugins:
  - name: arbitrum
  - name: optimism